/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --include-runtime=false` (hash: 9bd7244b761b50755940700b9edeace5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/_worker.js/index");
	}
	interface Env {
		GUESTBOOK_DB: D1Database;
		GUESTBOOK_IP_LIMITER: RateLimit;
		GUESTBOOK_GLOBAL_LIMITER: RateLimit;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
